name: Run tests

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install -U pip
      - name: Install pytest
        run: python -m pip install pytest
      - name: Install pynom/requirements
        run: python -m pip install .
      - name: Run pytest
        run: python -m pytest

  release:
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pypi:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        working-directory: ${{ github.workspace }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*

  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Generate docs
      run: |
        cd $GITHUB_WORKSPACE
        ls
        python3 --version
        sudo apt-get install python3-setuptools -y
        python3.7 -m pip install .

        python3.7 generate_docs.py

        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

        git add docs/* || true
        git add README.md || true
        git commit -a -m "Updating docs" || true
        git push origin master || true